<a href="https://colab.research.google.com/github/chaeyeongSon/pdm09/blob/master/numpy/numpy_2_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy array

- 생성
- 구조 살펴보기
- 수학연산 (columnwise, rowwise)

In [ ]:
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# summarize the array shape
print(data.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


## Print rows

In [ ]:
# enumerate rows in a numpy array
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# step through rows
for row in range(data.shape[0]):	# shape의 첫번째 요소 -> 행
	print(data[row, :])

[1 2 3]
[4 5 6]


## Print columns

In [ ]:
data

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# enumerate rows in a numpy array
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
print(data)
# step through columns
for col in range(data.shape[1]):	# shape의 두번째 요소 -> 열
	print(data[:, col])	

[[1 2 3]
 [4 5 6]]
[1 4]
[2 5]
[3 6]


## NumPy Array Operations By Row and Column
- axis=None: Apply operation array-wise.
- axis=0: Apply operation column-wise, across all rows for each column.
- axis=1: Apply operation row-wise, across all columns for each row.

In [ ]:
# sum values array-wise
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# sum data by array
result = data.sum(axis=None)  # 행렬의 모든 요소들의 합
# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
21


### Axis=0 Column-Wise Operation (수직으로)

In [ ]:
# sum values column-wise
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# sum data by column
result = data.sum() # 아무것도 기입하지 않으면 default 값으로 None이 들어감
result = data.sum(axis = 0) # 같은 열끼리 더해짐
# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
[5 7 9]


### Axis=1 Row-Wise Operation (수평으로)

In [ ]:
# sum values row-wise
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# sum data by row
result = data.sum(axis=1) # 같은 행끼리 더해짐
# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
[ 6 15]


## [Challenge]
- 3d-array
    * axis = 0
    * axis = 1
    * axis = 2
    * axis = (0,1)

## [도전하기]

- 3차원 배열을 리스트로부터 만드시오.

In [ ]:
# Make 3d-array in numpy
'''
data = [[1,2,3], [4,5,6]]
'''

In [ ]:
from numpy import asarray
data3d = [[1,2,3], [4,5,6], [7,8,9]]  # 2차원
data3d = asarray(data3d)
print(data3d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
data3d.ndim

2

### 3차원 배열:nXmXl, (n,m,l)

In [ ]:
data3d = [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]
data3d = asarray(data3d)
data3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
data3d.shape

(3, 2, 3)

In [ ]:
data3d.ndim

3

In [ ]:
data3d.sum()  # 2차원과 마찬가지로 default 값은 None로 모든 요소들의 합
# 1+2+3+4+5+6+1+2+3+4+5+6+1+2+3+4+5+6

63

In [ ]:
data3d.sum(axis=0)  # axis=0이면 첫번째 괄호가 사라졌을 때 남은 2차원 원소가 하나로 더해짐
# [[1+1+1+, 2+2+2, 3+3+3], [4+4+4, 5+5+5, 6+6+6+]]

array([[ 3,  6,  9],
       [12, 15, 18]])

In [ ]:
data3d.sum(axis=1)  # axis=1이면 두번째 괄호가 사라지면서 남는 1차원 원소가 하나로 더해짐
# [[1+4, 2+5, 3+6], [1+4, 2+5, 3+6], [1+4, 2+5, 3+6]]

array([[5, 7, 9],
       [5, 7, 9],
       [5, 7, 9]])

In [ ]:
data3d.sum(axis=2) # axis=2이면 3번째 괄호가 사라지면서 남는 스칼라 원소가 하나로 더해짐
# [[1+2+3, 4+5+6], [1+2+3, 4+5+6], [1+2+3, 4+5+6]]

array([[ 6, 15],
       [ 6, 15],
       [ 6, 15]])

In [ ]:
data3d.sum(axis=(0,1)) # axis=(0,1)이면 첫번째, 두번째 괄호가 사라지면서 남는 1차원 배열의 대응하는 원소끼리 더해짐
# [1+4+1+4+1+4, 2+5+2+5+2+5, 3+6+3+6+3+6]

array([15, 21, 27])

In [ ]:
data3d.sum(axis=(0,2))  # axis=(0,1)이면 첫번째, 세번째 괄호가 사라지면서 남는 1차원 배열의 대응하는 원소끼리 더해짐
# [1+2+3+1+2+3+1+2+3, 4+5+6+4+5+6+4+5+6]

array([18, 45])

In [ ]:
data3d.sum(axis=(1,2)) # axis = (1,2)이면 두번째, 세번째 괄호가 사라지면서 남는 스칼라가 모두 더해짐
# [1+2+3+4+5+6, 1+2+3+4+5+6, 1+2+3+4+5+6]

array([21, 21, 21])

### 위의 3차원 배열에 대한 계산 결과를 간단히 주석으로 설명해보세요.